theme: minima
title: New Relic NerdGraph API Client
tagline: A Node.js API Client for NerdGraph
description: A Node.js API Client for NerdGraph, the GraphQL API of New Relic that supports both synchronous and asynchronous NRQL queries.
# social links
twitter_username: Vinit_Shahdeo
github_username:  vinitshahdeo
author: Vinit Shahdeo
twitter:
  username: Vinit_Shahdeo
  card: summary
social_links:
  - { platform: github,         user_url: "https://github.com/vinitshahdeo" }
  - { platform: linkedin,       user_url: "https://www.linkedin.com/in/vinitshahdeo" }
  - { platform: twitter,        user_url: "https://twitter.com/vinit_shahdeo" }

plugins:
  - jekyll-seo-tag
